packages:
  # all packages in subdirs of packages/ and examples/
  - 'packages/**'
  - 'examples/**'
  - '!examples/**/_TODO/**'
  - 'docs/**'
  - 'test/**'
  - '!**/.tmp/**'
options:
  prefer-workspace-packages: true
  strict-peer-dependencies: false
