name: 📜 Docs Checks

on:
  merge_group:
  pull_request:
    paths:
      - "docs/**"
      - "package.json"
      - "pnpm-lock.yaml"

    branches:
      - main

jobs:
  docs:
    name: "📜 Docs successfully build"

    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build docs
        run: pnpm run docs:build
