name: 'Close issues'

on:
  issues:
    types: [labeled]

jobs:
  questions:
    runs-on: ubuntu-latest
    steps:
      - name: Close Issue
        uses: peter-evans/close-issue@v3
        if: "${{ github.event.label.name == ':speech_balloon: Question' }}"
        with:
          comment: Please note this issue tracker is not a help forum. We recommend using [Discussions](https://github.com/solidjs/solid-start/discussions/categories/q-a) for questions.
